### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by segantii-alex-falkowski** [KiraLT/Bjax#1]
Could you please add bower support http://bower.io/docs/creating-packages/

**Comment by KiraLT** [comment]
Bower support added: https://github.com/KiraLT/Bjax#download-using-bower

**Comment by segantii-alex-falkowski** [comment]
We use https://rails-assets.org/ which uses bower underneath. This package to work needs to be pushed to the bower servers. If you can't do that that is cool.

**Comment by KiraLT** [comment]
Bjax added to bower servers. Now you can just use `bower install bjax`.
